### ISSUE TITLE
Nativescript-theme-core css is not being imported

### ISSUE THREAD

**Issue by RosilBelli** [nativescript-vue/vue-cli-template#90]
### Version
N/A

### Reproduction link
[https://github.com/RosilBelli/Issue-Code](https://github.com/RosilBelli/Issue-Code)
### Platform and OS info
Android 8 / NS 4 / Windows 10

### Steps to reproduce
Commented the default SCSS import;

Added:
@import '~nativescript-theme-core/css/core.light.android.css'; 

### What is expected?
CSS classes to be available and working

### What is actually happening?
Not working

---
Even though importing the theme css in styles.scss file, it is not applied to the ui and I can't figure out why.

**Comment by rigor789** [comment]
Can you try without the `~` in the path? I suspect that has been changed somewhere recently (can't recall)

**Comment by RosilBelli** [comment]
I had already tried without (build error) and with a `/` (build is ok) but it still does not work.

**Comment by rigor789** [comment]
Okay, was worth a try. Will check this later!

**Comment by benc-uk** [comment]
Having the same issue
Creating a vanilla app from the template I'm not seeing any of the styles applied correctly

**Comment by benc-uk** [comment]
Ok, I removed the `~` and it briefly worked. Then I made a small change to `styles.scss` and the app is bust again and none of the list item styles are being applied

This is my first time trying nativescript-vue and it is driving me crazy, the behaviour seems both broken out of the box and also random

my styles.scss looks like
```scss
// NativeScript core theme
// @see https://docs.nativescript.org/ui/theme
@import 'nativescript-theme-core/scss/light';

// Override variables here

@import 'nativescript-theme-core/scss/index';

// Global SCSS styling
// @see https://docs.nativescript.org/ui/styling

.foo {
  color: red;
}
```

I've tired the .css files too e.g. `@import '~nativescript-theme-core/css/core.light.android.css';` that also doesn't work

Trying with and without the `~` also makes no difference
